L = {}

-- [[ Trivia ]]

L["eft_trivia_author"] = "Autor"
L["eft_trivia_assets"] = "Archivos"
L["eft_trivia_help"] = "Ayuda general"
L["eft_trivia_arc9"] = "ARC9 Base"

L["eft_trivia_manuf"] = "Manufactura"
L["eft_trivia_cal"] = "Calibre"
L["eft_trivia_act"] = "Acción"
L["eft_trivia_country"] = "Paiz"
L["eft_trivia_year"] = "Año"

L["eft_trivia_manuf_kalash"] = "Empresa Kalashnikov"
L["eft_trivia_manuf_molot"] = "Molot Oruzhie"
L["eft_trivia_manuf_tula"] = "Fábrica De Armas Tula"
L["eft_trivia_manuf_tskib"] = "TsKIB SOO"
L["eft_trivia_manuf_kbp"] = "Oficina de Diseno de Instrumentos KBP "

L["eft_trivia_act_bolt"] = "Manualmente"
L["eft_trivia_act_blow"] = "Blowback"
L["eft_trivia_act_gas"] = "Gas"
L["eft_trivia_act_recoil"] = "Retroceso"

L["eft_trivia_country_ussr"] = "Unión Soviética"
L["eft_trivia_country_rus"] = "Federacion de Rusia"
L["eft_trivia_country_belg"] = "Reino de Belgica"
L["eft_trivia_country_brit"] = "Reino Unido"
L["eft_trivia_country_usa"] = "EE. UU."
L["eft_trivia_country_usa_eu"] = "EE. UU./Europa"
L["eft_trivia_country_aust"] = "República de Austria"
L["eft_trivia_country_germ"] = "Alemania"
L["eft_trivia_country_italy"] = "Italia"

-- [[ Weapon Categories ]]
L["eft_subcat_carb"] = "5Carabina de asalto"
L["eft_subcat_ar"] = "1Fusil de asalto"
L["eft_subcat_sg"] = "6Escopeta"
L["eft_subcat_snip"] = "4Francotirador"
L["eft_subcat_smg"] = "2Subfusil"
L["eft_subcat_pist"] = "7Pistola"
L["eft_subcat_grenades"] = "8Granadas y Lanzagranadas"

-- [[ Weapon Classes ]]
L["eft_class_weapon_singleshot"] = "Fusil de tiro unico"
L["eft_class_weapon_boltsg"] = "Escopeta Manualmente"
L["eft_class_weapon_pist"] = "Pistola"
L["eft_class_weapon_revol"] = "Revolver"
L["eft_class_weapon_megapist"] = "Pistola Ametralladora"
L["eft_class_weapon_smg"] = "Pistola Ametralladora"
L["eft_class_weapon_ar"] = "Fusil de asalto"
L["eft_class_weapon_carb"] = "Carabina"
L["eft_class_weapon_semisg"] = "Escopeta Semiautomática"
L["eft_class_weapon_pumpsg"] = "Escopeta De Bombeo"
L["eft_class_weapon_lmg"] = "Ametralladora"
L["eft_class_weapon_boltsnip"] = "Francotirador Manualmente"
L["eft_class_weapon_marks"] = "	Fusil de tirador designado"
L["eft_class_weapon_dualsg"] = "Escopeta De Fuego selectivo"
L["eft_class_weapon_melee"] = "Arma de Combate cuerpo a cuerpo"
L["eft_class_weapon_grenade"] = "Granada de mano"
L["eft_class_weapon_flashbang"] = "Granada aturdidora"
L["eft_class_weapon_improvised_grenade"] = "Granada de mano improvisado"
L["eft_class_weapon_stun"] = "Granada aturdidora"
L["eft_class_weapon_smoke"] = "Granada de humo"
L["eft_class_weapon_grenadelauncher"] = "Lanzagranadas"

-- [[ Weapon Display Names ]]
L["eft_weapon_rsh12"] = "RSh-12"
L["eft_weapon_ash12"] = "ASh-12"
L["eft_weapon_toz106"] = "TOZ-106"
L["eft_weapon_ak74"] = "AK-74"
L["eft_weapon_ak74n"] = "AK-74N"
L["eft_weapon_ak74m"] = "AK-74M"
L["eft_weapon_aks74"] = "AKS-74"
L["eft_weapon_aks74n"] = "AKS-74N"
L["eft_weapon_aks74u"] = "AKS-74U"
L["eft_weapon_aks74un"] = "AKS-74UN"
L["eft_weapon_aks74ub"] = "AKS-74UB"
L["eft_weapon_ak101"] = "AK-101"
L["eft_weapon_ak102"] = "AK-102"
L["eft_weapon_ak103"] = "AK-103"
L["eft_weapon_ak104"] = "AK-104"
L["eft_weapon_ak105"] = "AK-105"
L["eft_weapon_akm"] = "AKM"
L["eft_weapon_akmn"] = "AKMN"
L["eft_weapon_akms"] = "AKMS"
L["eft_weapon_akmsn"] = "AKMSN"
L["eft_weapon_pp1901"] = "PP-19-01 \"Vityaz\""
L["eft_weapon_rpk16"] = "RPK-16"
L["eft_weapon_saiga9"] = "Saiga-9"
L["eft_weapon_saiga12k"] = "Saiga 12ga ver.10"
L["eft_weapon_vpo136"] = "VPO-136 \"Vepr-KM\""
L["eft_weapon_vpo209"] = "VPO-209"
L["eft_weapon_mosininf"] = "Mosin rifle (Infantry)"
L["eft_weapon_mosinsnip"] = "Mosin rifle (Sniper)"
L["eft_weapon_ks23"] = "TOZ KS-23M"

L["eft_weapon_rdg2b"] = "RDG-2B"
L["eft_weapon_rgd5"] = "RGD-5"
L["eft_weapon_rgn"] = "RGN"
L["eft_weapon_rgo"] = "RGO"
L["eft_weapon_vog17"] = "VOG-17 Khattabka"
L["eft_weapon_vog25"] = "VOG-25 Khattabka"
L["eft_weapon_zarya"] = "Zarya"

L["eft_weapon_6x5"] = "6Kh5 Bayonet"
L["eft_weapon_a2607"] = "Bars A-2607"
L["eft_weapon_a2607d"] = "Bars A-2607 Damascus"
L["eft_weapon_camper"] = "Camper axe"
L["eft_weapon_freeman"] = "Freeman crowbar"
L["eft_weapon_cultist"] = "Cultist knife"
L["eft_weapon_mpl50"] = "MPL-50 entr. tool"
L["eft_weapon_rebel"] = "Red Rebel ice pick"
L["eft_weapon_sp8"] = "SP-8 Machete"
L["eft_weapon_taiga"] = "UVSR Taiga-1"
L["eft_weapon_wycc"] = "Antique axe"



L["eft_weapon_veresk"] = "SR-2M \"Veresk\""
L["eft_weapon_gyurza"] = "SR-1MP Gyurza"
L["eft_trivia_manuf_tsniitochmash"] = "TsNIITochMash"
L["eft_trivia_calibr_9x21"] = "9x21mm Gyurza"


L["eft_hud_full"] = "Lleno"
L["eft_hud_empty"] = "Vacío"
L["eft_hud_nearlyfull"] = "Casi Lleno"
L["eft_hud_aboutfull"] = "Casi Medio"
L["eft_hud_lessthanhlaf"] = "Menos De Medio"
L["eft_hud_almostempty"] = "Casi Vacío"
L["eft_hud_none"] = "Nada"
L["eft_hud_malf"] = "Mal Funcionamiento: \""
L["eft_hud_misfire"] = "Error De Tiro"
L["eft_hud_eject"] = "Fallo Al Expulsar"
L["eft_hud_feed"] = "Fallo Al Cebar"
L["eft_hud_bolt"] = "Cerrojo Atorado"
L["eft_hud_missing"] = "Faltan Partes Esenciales!"


-- [[ Weapon descs ]] CHINGAOOOOOOOO WE
-- L["eft_weapon_vpo209"] = "VPO-209"

