$modelname "weapons/arc9_eft_shared/atts/mounts/casv.mdl"

$scale 40

// $cdmaterials "models/weapons/arc9_eft_shared/atts/mounts/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body"
{
	studio "mount_casv_vltor_2_inch_picatinny_rail_section_LOD0.smd" // 0
	studio "mount_casv_vltor_4_inch_picatinny_rail_section_LOD0.smd" // 1
	studio "mount_casv_vltor_5_inch_picatinny_rail_section_LOD0.smd" // 2
}

$sequence "idle" {
	"..\Plane.smd"
}