$modelname "weapons/arc9_eft_shared/atts/mounts/keymod_corvus.mdl"

$scale 40

// $cdmaterials "models/weapons/arc9_eft_shared/atts/mounts/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body"
{
	studio "mount_keymod_corvus_defencio_1_8_inch_rail_section_LOD0.smd" // 0
	studio "mount_keymod_corvus_defencio_6_8_inch_rail_section_LOD0.smd" // 1
}

$sequence "idle" {
	"..\Plane.smd"
}