$modelname "weapons/arc9_eft_shared/atts/optic/dovetail/1p29_eyecap.mdl"

$scale 40

$cdmaterials "models/weapons/arc9_eft_shared/atts/optic/dovetail/"

$bodygroup "body"
{
	studio "tactical_1p29_npz_eyecup_LOD0_0.smd" // 0
}

// $texturegroup skinfamilies
// {
// 	{ "mount_hex_hexagon_short_LOD0" "mount_hex_hexagon_medium_LOD0"  }
// 	{ "mount_hex_hexagon_short_LOD0_red" "mount_hex_hexagon_medium_LOD0_red" }
// }

$sequence "idle" {
	"..\Plane.smd"
}