L = {}

//////////////////////////////////////////////////////////////////////
///////////////////////////// Escape from Tarkov Localization File - Unofficial UwU-ified English
////////////// EFT General Strings
-- [[ HUD ]]
L["eft_hud_full"] = "Fuwl :3"
L["eft_hud_empty"] = "Emptwy >.<"
L["eft_hud_nearlyfull"] = "Neawwy fuwl"
L["eft_hud_aboutfull"] = "Abuwut haww >w<"
L["eft_hud_lessthanhlaf"] = "Lewss twan haww"
L["eft_hud_almostempty"] = "Awmowst emptwy !"
L["eft_hud_none"] = "None uwu"
L["eft_hud_malf"] = "Mawwwunktiwon!!!! \""
L["eft_hud_misfire"] = "Miwwfiwe :3"
L["eft_hud_eject"] = "Faiwuwe to ewect owo"
L["eft_hud_feed"] = "Faiwuwe to fewd >w<"
L["eft_hud_bolt"] = "Bowt jam !!"
L["eft_hud_missing"] = "Miwwing cwiticawal pawts owo"
L["eft_hud_badtrip"] = "Pwant umawaiwabel" -- kill me

-- [[ Weapon Classes ]] - Need to be edited manually
L["eft_class_weapon_singleshot"] = "Single-shot Wifle"
L["eft_class_weapon_boltsg"] = "Bowt-actiowon Showtgun"
L["eft_class_weapon_pist"] = "Pistow"
L["eft_class_weapon_revol"] = "Rowowwer"
L["eft_class_weapon_megapist"] = "Machwine Pistow"
L["eft_class_weapon_smg"] = "Suwubmawwine Guwn"
L["eft_class_weapon_ar"] = "Awwault Wifle"
L["eft_class_weapon_carb"] = "Awwault Cawwbine"
L["eft_class_weapon_semisg"] = "Semi-autowo Showtgun"
L["eft_class_weapon_autosg"] = "Autowo Showtgun"
L["eft_class_weapon_pumpsg"] = "Puwump Showtgun"
L["eft_class_weapon_lmg"] = "Liwwt Machwine Guwn"
L["eft_class_weapon_boltsnip"] = "Bowt-actiowon Sniper Wifle"
L["eft_class_weapon_marks"] = "Mawksmwan Wifle"
L["eft_class_weapon_dualsg"] = "Duwal-mowode Showtgun"
L["eft_class_weapon_melee"] = "Mewwee weapwon"
-- L["eft_class_weapon_toy"] = "Toy Gun"
-- L["eft_class_weapon_signalpis"] = "Signal pistol"
-- L["eft_class_weapon_dbsg"] = "Double-barrel shotgun"

L["eft_class_weapon_grenade"] = "Hawand Gwenad owo"
L["eft_class_weapon_flashbang"] = "Fwawh Bawang Gwenad >w<"
L["eft_class_weapon_improvised_grenade"] = "Impwowised Hand Gwenad"
L["eft_class_weapon_stun"] = "StUwUn Gwenad"
L["eft_class_weapon_smoke"] = "SmOwOke Gwenad"
L["eft_class_weapon_grenadelauncher"] = "Gwenad wauncheww"
-- L["eft_class_weapon_special"] = "Special item"

-- [[ Weapon Categories ]] - If not using localized strings
L["eft_subcat_carb"] = "5Awwault Cawwbines owo"
L["eft_subcat_ar"] = "1Awwault Wiffles uwu"
L["eft_subcat_sg"] = "6Showtguwuns"
L["eft_subcat_snip"] = "4Snipew/Mawksmwan Wifles"
L["eft_subcat_smg"] = "2Suwubmawwine Guwns"
L["eft_subcat_lmg"] = "3Lighht mawwine Guwns"
L["eft_subcat_pist"] = "7Pistows"
L["eft_subcat_melee"] = "9Mewwee"
L["eft_subcat_grenades"] = "8Gwenads  aawnd gwenade waunchews uwu"

////////////// Non-EFT Strings
-- [[ Trivia ]]
L["eft_trivia_author"] = "Authowow :3"
L["eft_trivia_assets"] = "Awwets"
L["eft_trivia_help"] = "Genewaw hewp"
L["eft_trivia_arc9"] = "AWC9 Bawe dumb! >w<"
-- L["eft_trivia_anim"] = "Custom animations"

L["eft_trivia_manuf"] = "Manuwactuwew owo"
L["eft_trivia_cal"] = "Cawibww"
L["eft_trivia_act"] = "Actiwon"
L["eft_trivia_country"] = "Countwy uwu"
L["eft_trivia_year"] = "Yeaww"

L["eft_trivia_unknown"] = "Unknown"

L["eft_trivia_manuf_adar"] = "ADAR"
L["eft_trivia_manuf_ai"] = "Accuracy International"
L["eft_trivia_manuf_aklys"] = "Aklys Defense"
L["eft_trivia_manuf_benelli"] = "Benelli Armi S.p.A."
L["eft_trivia_manuf_beretta"] = "Fabbrica d'Armi Pietro Beretta"
L["eft_trivia_manuf_bt"] = "B&T AG"
L["eft_trivia_manuf_chiappa"] = "Armi Sport di Chiappa"
L["eft_trivia_manuf_cmmg"] = "CMMG Inc."
L["eft_trivia_manuf_colt"] = "Colt's Manufacturing Company"
L["eft_trivia_manuf_degtyaryov"] = "Degtyaryov Plant"
L["eft_trivia_manuf_deserttech"] = "Desert Tech"
L["eft_trivia_manuf_dsarms"] = "DS Arms"
L["eft_trivia_manuf_fnherstal"] = "FN Herstal"
L["eft_trivia_manuf_fnherstal_xproducts"] = "FN Herstal + X Products"
L["eft_trivia_manuf_glock"] = "Glock Ges.m.b.H."
L["eft_trivia_manuf_hk"] = "Heckler & Koch"
L["eft_trivia_manuf_iwi"] = "Israel Weapon Industries"
L["eft_trivia_manuf_izhevsk"] = "Izhevsk Mechanical Plant"
L["eft_trivia_manuf_izhmash"] = "Izhmash"
L["eft_trivia_manuf_kac"] = "Knight's Armament Company"
L["eft_trivia_manuf_kalash"] = "Kalashnikov Concern"
L["eft_trivia_manuf_kbp"] = "KBP Instrument Design Bureau"
L["eft_trivia_manuf_keltec"] = "Kel-Tec CNC Industries Inc."
L["eft_trivia_manuf_kriss"] = "Transformational Defense Industries (TDI)"
L["eft_trivia_manuf_lobaev"] = "Lobaev Arms (KBIS)"
L["eft_trivia_manuf_lonestar"] = "Lone Star Armory"
L["eft_trivia_manuf_magnumresearch"] = "Magnum Research"
L["eft_trivia_manuf_milkor"] = "Milkor (Pty) Ltd"
L["eft_trivia_manuf_molot"] = "Molot Oruzhie"
L["eft_trivia_manuf_mossberg"] = "O.F. Mossberg & Sons"
L["eft_trivia_manuf_mps"] = "Military Police Systems"
L["eft_trivia_manuf_npo"] = "NPO Bazalt"
L["eft_trivia_manuf_orsis"] = "ORSIS"
L["eft_trivia_manuf_remington"] = "Remington Arms Company, LLC"
L["eft_trivia_manuf_rifledynamics"] = "Rifle Dynamics"
L["eft_trivia_manuf_sako"] = "Sako"
L["eft_trivia_manuf_sig"] = "SIG Sauer"
L["eft_trivia_manuf_soyus"] = "Soyus-TM Arms"
L["eft_trivia_manuf_springfield"] = "Springfield Armory"
L["eft_trivia_manuf_steyr"] = "Steyr Arms"
L["eft_trivia_manuf_sureshot"] = "Sureshot Armament Group"
L["eft_trivia_manuf_sword"] = "SWORD International"
L["eft_trivia_manuf_tskib"] = "TsKIB SOO"
L["eft_trivia_manuf_tsniitochmash"] = "TsNIITochMash"
L["eft_trivia_manuf_tula"] = "Tula Arms Plant"
L["eft_trivia_manuf_usordnance"] = "U.S. Ordnance"
L["eft_trivia_manuf_vytatsky"] = "Vytatsky Polyany Machine-Building Plant"
L["eft_trivia_manuf_zmz"] = "ZMZ"

L["eft_trivia_manuf_tarkovtoy"] = "Tarkov's Sector for Fun Activities"
L["eft_trivia_manuf_numerous"] = "Numerous"

L["eft_trivia_country_ussr"] = "Sowiet Uniown uwu"
L["eft_trivia_country_rus"] = "Rusian Fedewation owo"
L["eft_trivia_country_belg"] = "Kingw-dom of Bewgium"
L["eft_trivia_country_brit"] = "Uniwed Kinwgdom"
L["eft_trivia_country_usa"] = "USwA 'w'"
L["eft_trivia_country_usa_eu"] = "USwA/Euwuwope"
L["eft_trivia_country_aust"] = "Wepublwic of Austwia"
L["eft_trivia_country_germ"] = "Gewmany"
L["eft_trivia_country_italy"] = "Itawy owo"
-- L["eft_trivia_country_finland"] = "Finland"
-- L["eft_trivia_country_switzerland"] = "Switzerland"
-- L["eft_trivia_country_israel"] = "Israel"

L["eft_trivia_act_bolt"] = "Bowt >w<"
L["eft_trivia_act_blow"] = "Bwow uwu"
L["eft_trivia_act_gas"] = "Gaws owo"
L["eft_trivia_act_recoil"] = "Wecoil uwu"

L["eft_trivia_calibr_762x25"] = "7.62x25mm Tokarev"
L["eft_trivia_calibr_9x18"] = "9x18mm Makarov"
L["eft_trivia_calibr_9x19"] = "9x19mm Parabellum"
L["eft_trivia_calibr_9x21"] = "9x21mm Gyurza"
L["eft_trivia_calibr_357"] = ".357 Magnum"
L["eft_trivia_calibr_45acp"] = ".45 ACP"
L["eft_trivia_calibr_50ae"] = ".50 Action Express"
L["eft_trivia_calibr_20x1"] = "20x1mm"

L["eft_trivia_calibr_46x30"] = "4.6x30mm HK"
L["eft_trivia_calibr_57x28"] = "5.7x28mm FN"

L["eft_trivia_calibr_545x39"] = "5.45x39mm"
L["eft_trivia_calibr_556x45"] = "5.56x45mm NATO"
L["eft_trivia_calibr_68x51"] = "6.8x51mm"
L["eft_trivia_calibr_762x35"] = "7.62x35mm (.300 Blackout)"
L["eft_trivia_calibr_762x39"] = "7.62x39mm"
L["eft_trivia_calibr_762x51"] = "7.62x51mm NATO"
L["eft_trivia_calibr_762x54"] = "7.62x54mmR"
L["eft_trivia_calibr_338lm"] = "8.6x70mm (.338 Lapua Magnum)"
L["eft_trivia_calibr_9x39"] = "9x39mm"
L["eft_trivia_calibr_366tkm"] = ".366 TKM"
L["eft_trivia_calibr_127x55"] = "12.7x55mm"
L["eft_trivia_calibr_127x108"] = "12.7x108mm"

L["eft_trivia_calibr_12g"] = "12/70 (12 gauge)"
L["eft_trivia_calibr_20g"] = "20/70 (20 gauge)"
L["eft_trivia_calibr_4g"] = "23x75mmR (4 gauge)"

L["eft_trivia_calibr_30x29"] = "30x29mm"
L["eft_trivia_calibr_40x46"] = "40x46mm"
L["eft_trivia_calibr_40x53"] = "40x53mm"

L["eft_trivia_calibr_26x75"] = "26x75mm"

L["eft_trivia_calibr_30flare"] = "30mm flare"
L["eft_trivia_calibr_725heat"] = "72.5mm HEAT"

L["eft_fmode_bolt"] = "Bolt"
L["eft_fmode_manualreload"] = "M. Reload"
L["eft_fmode_doubleaction"] = "D. Act."
L["eft_fmode_singleaction"] = "S. Act."
L["eft_fmode_melee"] = "Melee"
L["eft_fmode_grenade"] = "Grenade"
L["eft_fmode_pump"] = "Pump"
L["eft_fmode_throw"] = "Throw"
L["eft_fmode_tripwire"] = "Tripwire"
L["eft_fmode_singleshot"] = "Single"
L["eft_fmode_doubletap"] = "Double-Tap"

L["eft_toggle_off"] = "Off"

L["eft_toggle_folded"] = "Folded"
L["eft_toggle_unfolded"] = "Unfolded"

L["eft_toggle_thermalwhite"] = "White hot"
L["eft_toggle_thermalred"] = "Red hot"
L["eft_toggle_thermalpurple"] = "Purple hot"
L["eft_toggle_thermalyellow"] = "Yellow hot"

L["eft_toggle_screen"] = "Screen"

L["eft_toggle_light"] = "Light"

L["eft_toggle_laser"] = "Laser"
L["eft_toggle_laser_red"] = "Red laser"
L["eft_toggle_laser_green"] = "Green laser"
L["eft_toggle_laser_blue"] = "Blue laser"

L["eft_toggle_light_laser"] = "Light + Laser"
L["eft_toggle_light_laser_red"] = "Light + Red laser"
L["eft_toggle_light_laser_green"] = "Light + Green laser"
L["eft_toggle_light_laser_blue"] = "Light + Blue laser"

L["eft_toggle_light_ir"] = "IR Light"
L["eft_toggle_laser_ir"] = "IR Laser"
L["eft_toggle_light_laser_ir"] = "IR Light & Laser"
L["eft_toggle_searchlight_ir"] = "IR Searchlight"

L["eft_toggle_light_low"] = "Light, low power"
L["eft_toggle_laser_low"] = "Laser, low power"
L["eft_toggle_light_ir_low"] = "IR Light, low power"

L["eft_toggle_light_high"] = "Light, high power"
L["eft_toggle_laser_high"] = "Laser, high power"
L["eft_toggle_light_ir_high"] = "IR Light, high power"

-- [[ Customization ]]
L["Ergonomics"] = "Ergonomics"
-- L["Ergonomics.desc"] = "[ EFT ] Affects aim down sight speed and stamina drain."
