L = {}

-- [[ Trivia ]]

L["eft_trivia_author"] = "Автор"
L["eft_trivia_assets"] = "Ассеты"
L["eft_trivia_help"] = "Помощь"
L["eft_trivia_arc9"] = "База ARC9"

L["eft_trivia_manuf"] = "Производитель"
L["eft_trivia_cal"] = "Калибр"
L["eft_trivia_act"] = "Действие"
L["eft_trivia_country"] = "Страна"
L["eft_trivia_year"] = "Год"

L["eft_trivia_manuf_kalash"] = "Концерн «Калашников»"
L["eft_trivia_manuf_molot"] = "Молот-Оружие"
L["eft_trivia_manuf_tula"] = "Тульский оружейный завод"
L["eft_trivia_manuf_tskib"] = "ЦКИБ СОО"
L["eft_trivia_manuf_kbp"] = "Конструкторское бюро приборостроения"

L["eft_trivia_act_bolt"] = "Скользящий затвор"
L["eft_trivia_act_blow"] = "Свободный затвор"
L["eft_trivia_act_gas"] = "Отвод пороховых газов"
L["eft_trivia_act_recoil"] = "Отдача ствола"

L["eft_trivia_country_ussr"] = "Советский Союз"
L["eft_trivia_country_rus"] = "Российская Федерация"
L["eft_trivia_country_belg"] = "Королевство Белгия"
L["eft_trivia_country_brit"] = "Соединённое Королевство"
L["eft_trivia_country_usa"] = "США"
L["eft_trivia_country_usa_eu"] = "США/Европа"
L["eft_trivia_country_aust"] = "Австрийская Республика"
L["eft_trivia_country_germ"] = "Германия"
L["eft_trivia_country_italy"] = "Италия"

-- [[ Weapon Categories ]]
L["eft_subcat_carb"] = "5Штурмовые карабины"
L["eft_subcat_ar"] = "1Штурмовые винтовки"
L["eft_subcat_sg"] = " 6Дробовики"
L["eft_subcat_snip"] = "4Снайперские и марксманские винтовки"
L["eft_subcat_smg"] = "2Пистолеты-пулеметы"
L["eft_subcat_lmg"] = "3Пулеметы"
L["eft_subcat_pist"] = "7Пистолеты"
L["eft_subcat_melee"] = "9Ближний бой"
L["eft_subcat_grenades"] = "8Гранаты и гранатомёты"

-- [[ Weapon Classes ]]
L["eft_class_weapon_singleshot"] = "Однозарядное ружье"
L["eft_class_weapon_boltsg"] = "Болтовое ружье"
L["eft_class_weapon_pist"] = "Пистолет"
L["eft_class_weapon_revol"] = "Револьвер"
L["eft_class_weapon_megapist"] = "Автоматический пистолет"
L["eft_class_weapon_smg"] = "Пистолет-пулемет"
L["eft_class_weapon_ar"] = "Штурмовая винтовка"
L["eft_class_weapon_carb"] = "Штурмовой карабин"
L["eft_class_weapon_semisg"] = "Самозарядный карабин"
L["eft_class_weapon_autosg"] = "Автоматический дробовик"
L["eft_class_weapon_pumpsg"] = "Помповое ружье"
L["eft_class_weapon_lmg"] = "Ручной пулемет"
L["eft_class_weapon_boltsnip"] = "Болтовая снайперская винтовка"
L["eft_class_weapon_marks"] = "Марксманская винтовка"
L["eft_class_weapon_dualsg"] = "Ружьё"
L["eft_class_weapon_melee"] = "Оружие ближнего боя"

L["eft_class_weapon_melee"] = "Оружие ближнего боя"
L["eft_class_weapon_grenade"] = "Ручная граната"
L["eft_class_weapon_flashbang"] = "Светозвуковая граната"
L["eft_class_weapon_improvised_grenade"] = "Самодельная ручная граната"
L["eft_class_weapon_stun"] = "Оглушающая граната"
L["eft_class_weapon_smoke"] = "Дымовая граната"
L["eft_class_weapon_grenadelauncher"] = "Гранатомёт"

-- [[ Weapon Display Names ]]
L["eft_weapon_rsh12"] = "РШ-12"
L["eft_weapon_ash12"] = "АШ-12"
L["eft_weapon_toz106"] = "ТОЗ-106"
L["eft_weapon_ak74"] = "АК-74"
L["eft_weapon_ak74n"] = "АК-74Н"
L["eft_weapon_ak74m"] = "АК-74М"
L["eft_weapon_aks74"] = "АКС-74"
L["eft_weapon_aks74n"] = "АКС-74Н"
L["eft_weapon_aks74u"] = "АКС-74У"
L["eft_weapon_aks74un"] = "АКС-74УН"
L["eft_weapon_aks74ub"] = "АКС-74УБ"
L["eft_weapon_ak101"] = "АК-101"
L["eft_weapon_ak102"] = "АК-102"
L["eft_weapon_ak103"] = "АК-103"
L["eft_weapon_ak104"] = "АК-104"
L["eft_weapon_ak105"] = "АК-105"
L["eft_weapon_akm"] = "АКМ"
L["eft_weapon_akmn"] = "АКМН"
L["eft_weapon_akms"] = "АКМС"
L["eft_weapon_akmsn"] = "АКМСН"
L["eft_weapon_pp1901"] = "ПП-19-01 \"Витязь\""
L["eft_weapon_rpk16"] = "РПК-16"
L["eft_weapon_saiga9"] = "Сайга-9"
L["eft_weapon_saiga12k"] = "Сайга-12К исп.10"
L["eft_weapon_vpo136"] = "ВПО-136 \"Вепрь-КМ\""
L["eft_weapon_vpo209"] = "ВПО-209"
L["eft_weapon_mosininf"] = "Винтовка Мосина (Пехот.)"
L["eft_weapon_mosinsnip"] = "Винтовка Мосина (Снайпер.)"
L["eft_weapon_ks23"] = "ТОЗ КС-23М"

L["eft_weapon_rdg2b"] = "РДГ-2Б"
L["eft_weapon_rgd5"] = "РГД-5"
L["eft_weapon_rgn"] = "РГН"
L["eft_weapon_rgo"] = "РГО"
L["eft_weapon_vog17"] = "Хаттабка ВОГ-17"
L["eft_weapon_vog25"] = "Хаттабка ВОГ-25"
L["eft_weapon_zarya"] = "Заря"

L["eft_weapon_6x5"] = "Штык-нож 6Х5"
L["eft_weapon_a2607"] = "Барс А-2607"
L["eft_weapon_a2607d"] = "Барс А-2607 Дамаск"
L["eft_weapon_camper"] = "Походный топор"
L["eft_weapon_freeman"] = "Лом Freeman"
L["eft_weapon_cultist"] = "Нож сектанта"
L["eft_weapon_mpl50"] = "Пехот. Лопата МПЛ-50"
L["eft_weapon_rebel"] = "Ледоруб Red Rebel"
L["eft_weapon_sp8"] = "Мачете SP-8"
L["eft_weapon_taiga"] = "УВСР Тайга-1"
L["eft_weapon_wycc"] = "Антикварный топор	"

L["eft_weapon_veresk"] = "СР-2М \"Вереск\""
L["eft_weapon_gyurza"] = "СР-1МП Гюрза"
L["eft_trivia_manuf_tsniitochmash"] = "АО «ЦНИИточмаш»"
L["eft_trivia_calibr_9x21"] = "9x21мм Гюрза"

L["eft_weapon_ak12"] = "AK-12"
L["eft_weapon_pkm"] = "ПКМ"
L["eft_weapon_pkp"] = "ПКП \"Печенег\""

L["eft_hud_full"] = "Полон"
L["eft_hud_empty"] = "Пуст"
L["eft_hud_nearlyfull"] = "Почти полон"
L["eft_hud_aboutfull"] = "Около половины"
L["eft_hud_lessthanhlaf"] = "Меньше половины"
L["eft_hud_almostempty"] = "Почти пуст"
L["eft_hud_none"] = "Пусто"
L["eft_hud_malf"] = "Неполадка: \""
L["eft_hud_misfire"] = "Осечка"
L["eft_hud_eject"] = "Неизвлечение гильзы"
L["eft_hud_feed"] = "Неподача патрона"
L["eft_hud_bolt"] = "Заклинивание затвора"
L["eft_hud_missing"] = "Отсутствуют критические части!"
L["eft_hud_badtrip"] = "Невозможно установить растяжку"


-- [[ Weapon descs ]] fuckkkkkkkk
-- L["eft_weapon_vpo209"] = "VPO-209"

