L = {}

-- [[ Trivia ]]

L["eft_trivia_author"] = "Autor"
L["eft_trivia_assets"] = "Arquivos"
L["eft_trivia_help"] = "Ajuda geral"
L["eft_trivia_arc9"] = "ARC9 Base"

L["eft_trivia_manuf"] = "Fabricação"
L["eft_trivia_cal"] = "Calibre"
L["eft_trivia_act"] = "Ação"
L["eft_trivia_country"] = "Pais"
L["eft_trivia_year"] = "ano"

L["eft_trivia_manuf_kalash"] = "Empresa Kalashnikov"
L["eft_trivia_manuf_molot"] = "Molot Oruzhie"
L["eft_trivia_manuf_tula"] = "Fábrica De Armas Tula"
L["eft_trivia_manuf_tskib"] = "TsKIB SOO"
L["eft_trivia_manuf_kbp"] = "Gabinete de Projeto de Instrumentos KBP"
L["eft_trivia_act_bolt"] = "Manualmente"
L["eft_trivia_act_blow"] = "Blowback"
L["eft_trivia_act_gas"] = "Gás"
L["eft_trivia_act_recoil"] = "Recuo"

L["eft_trivia_country_ussr"] = "União Soviética"
L["eft_trivia_country_rus"] = "Federação Russa"
L["eft_trivia_country_belg"] = "Reino da Bélgica"
L["eft_trivia_country_brit"] = "Reino Unido"
L["eft_trivia_country_usa"] = "EUA"
L["eft_trivia_country_usa_eu"] = "EUA/Europa"
L["eft_trivia_country_aust"] = "República da Áustria"
L["eft_trivia_country_germ"] = "Alemanha"
L["eft_trivia_country_italy"] = "Itália"

-- [[ Weapon Categories ]]
L["eft_subcat_carb"] = "Carabina de Assalto"
L["eft_subcat_ar"] = "Fuzil de assalto"
L["eft_subcat_sg"] = "Espingarda"
L["eft_subcat_snip"] = "Atirador"
L["eft_subcat_smg"] = "Pistola Metralhadora"
L["eft_subcat_pist"] = "Pistola"
L["eft_subcat_grenades"] = "Granadas e Lança-Granadas"

-- [[ Weapon Classes ]]
L["eft_class_weapon_singleshot"] = "Rifle de tiro único"
L["eft_class_weapon_boltsg"] = "Espingarda Manualmente"
L["eft_class_weapon_pist"] = "Pistola"
L["eft_class_weapon_revol"] = "Revólver"
L["eft_class_weapon_megapist"] = "Pistola Metralhadora"
L["eft_class_weapon_smg"] = "Pistola Metralhadora"
L["eft_class_weapon_ar"] = "Rifle de assalto"
L["eft_class_weapon_carb"] = "Carbina"
L["eft_class_weapon_semisg"] = "Espingarda Semiautomática"
L["eft_class_weapon_pumpsg"] = "Bomba Espingarda"
L["eft_class_weapon_lmg"] = "Metralhadora"
L["eft_class_weapon_boltsnip"] = "Atirador de mão"
L["eft_class_weapon_marks"] = "Rifle de atirador designado"
L["eft_class_weapon_dualsg"] = "Espingarda de Tiro Seletivo"
L["eft_class_weapon_melee"] = "Arma de Combate cuerpo a cuerpo"
L["eft_class_weapon_grenade"] = "Granada de mão"
L["eft_class_weapon_flashbang"] = "Granada de atordoamento"
L["eft_class_weapon_improvised_grenade"] = "Atirador de mão improvisado"
L["eft_class_weapon_stun"] = "Granada de atordoamento"
L["eft_class_weapon_smoke"] = "Granada de fumo"
L["eft_class_weapon_grenadelauncher"] = "Lança-Granadas"

-- [[ Weapon Display Names ]]
L["eft_weapon_rsh12"] = "RSh-12"
L["eft_weapon_ash12"] = "ASh-12"
L["eft_weapon_toz106"] = "TOZ-106"
L["eft_weapon_ak74"] = "AK-74"
L["eft_weapon_ak74n"] = "AK-74N"
L["eft_weapon_ak74m"] = "AK-74M"
L["eft_weapon_aks74"] = "AKS-74"
L["eft_weapon_aks74n"] = "AKS-74N"
L["eft_weapon_aks74u"] = "AKS-74U"
L["eft_weapon_aks74un"] = "AKS-74UN"
L["eft_weapon_aks74ub"] = "AKS-74UB"
L["eft_weapon_ak101"] = "AK-101"
L["eft_weapon_ak102"] = "AK-102"
L["eft_weapon_ak103"] = "AK-103"
L["eft_weapon_ak104"] = "AK-104"
L["eft_weapon_ak105"] = "AK-105"
L["eft_weapon_akm"] = "AKM"
L["eft_weapon_akmn"] = "AKMN"
L["eft_weapon_akms"] = "AKMS"
L["eft_weapon_akmsn"] = "AKMSN"
L["eft_weapon_pp1901"] = "PP-19-01 \"Vityaz\""
L["eft_weapon_rpk16"] = "RPK-16"
L["eft_weapon_saiga9"] = "Saiga-9"
L["eft_weapon_saiga12k"] = "Saiga 12ga ver.10"
L["eft_weapon_vpo136"] = "VPO-136 \"Vepr-KM\""
L["eft_weapon_vpo209"] = "VPO-209"
L["eft_weapon_mosininf"] = "Mosin rifle (Infantry)"
L["eft_weapon_mosinsnip"] = "Mosin rifle (Sniper)"
L["eft_weapon_ks23"] = "TOZ KS-23M"

L["eft_weapon_rdg2b"] = "RDG-2B"
L["eft_weapon_rgd5"] = "RGD-5"
L["eft_weapon_rgn"] = "RGN"
L["eft_weapon_rgo"] = "RGO"
L["eft_weapon_vog17"] = "VOG-17 Khattabka"
L["eft_weapon_vog25"] = "VOG-25 Khattabka"
L["eft_weapon_zarya"] = "Zarya"

L["eft_weapon_6x5"] = "6Kh5 Bayonet"
L["eft_weapon_a2607"] = "Bars A-2607"
L["eft_weapon_a2607d"] = "Bars A-2607 Damascus"
L["eft_weapon_camper"] = "Camper axe"
L["eft_weapon_freeman"] = "Freeman crowbar"
L["eft_weapon_cultist"] = "Cultist knife"
L["eft_weapon_mpl50"] = "MPL-50 entr. tool"
L["eft_weapon_rebel"] = "Red Rebel ice pick"
L["eft_weapon_sp8"] = "SP-8 Machete"
L["eft_weapon_taiga"] = "UVSR Taiga-1"
L["eft_weapon_wycc"] = "Antique axe"



L["eft_weapon_veresk"] = "SR-2M \"Veresk\""
L["eft_weapon_gyurza"] = "SR-1MP Gyurza"
L["eft_trivia_manuf_tsniitochmash"] = "TsNIITochMash"
L["eft_trivia_calibr_9x21"] = "9x21mm Gyurza"


L["eft_hud_full"] = "Cheio"
L["eft_hud_empty"] = "Vazio"
L["eft_hud_nearlyfull"] = "Quase cheio"
L["eft_hud_aboutfull"] = "Quase metade"
L["eft_hud_lessthanhlaf"] = "Menos que médio"
L["eft_hud_almostempty"] = "Quase Vazio"
L["eft_hud_none"] = "Nada"
L["eft_hud_malf"] = "Avaria: \""
L["eft_hud_misfire"] = "Falha de ignição"
L["eft_hud_eject"] = "Falha ao ejetar"
L["eft_hud_feed"] = "Falha no Prime"
L["eft_hud_bolt"] = "Parafuso preso"
L["eft_hud_missing"] = "Faltam peças essenciais!"


-- [[ Weapon descs ]] MEERRRDOOOO MANNOOO
-- L["eft_weapon_vpo209"] = "VPO-209"

