L = {}

-- [[ Trivia ]]

L["eft_trivia_author"] = "Authowow :3"
L["eft_trivia_assets"] = "Awwets"
L["eft_trivia_help"] = "Genewaw hewp"
L["eft_trivia_arc9"] = "AWC9 Bawe dumb! >w<"

L["eft_trivia_manuf"] = "Manuwactuwew owo"
L["eft_trivia_cal"] = "Cawibww"
L["eft_trivia_act"] = "Actiwon"
L["eft_trivia_country"] = "Countwy uwu"
L["eft_trivia_year"] = "Yeaww"

L["eft_trivia_manuf_kalash"] = "Kalawnikoww Concewn"
L["eft_trivia_manuf_molot"] = "Mowot Owwuzhie"
L["eft_trivia_manuf_tula"] = "Tuwa Awms Pwant"
L["eft_trivia_manuf_tskib"] = "TsKIB SOWO"
L["eft_trivia_manuf_kbp"] = "KBP Instwument Dewign Buweauwu"

L["eft_trivia_act_bolt"] = "Bowt >w<"
L["eft_trivia_act_blow"] = "Bwow uwu"
L["eft_trivia_act_gas"] = "Gaws owo"
L["eft_trivia_act_recoil"] = "Wecoil uwu"

L["eft_trivia_country_ussr"] = "Sowiet Uniown uwu"
L["eft_trivia_country_rus"] = "Rusian Fedewation owo"
L["eft_trivia_country_belg"] = "Kingw-dom of Bewgium"
L["eft_trivia_country_brit"] = "Uniwed Kinwgdom"
L["eft_trivia_country_usa"] = "USwA 'w'"
L["eft_trivia_country_usa_eu"] = "USwA/Euwuwope"
L["eft_trivia_country_aust"] = "Wepublwic of Austwia"
L["eft_trivia_country_germ"] = "Gewmany"
L["eft_trivia_country_italy"] = "Itawy owo"

-- [[ Weapon Categories ]]
L["eft_subcat_carb"] = "Awwault Cawwbines owo"
L["eft_subcat_ar"] = "Awwault Wiffles uwu"
L["eft_subcat_sg"] = "Showtguwuns"
L["eft_subcat_snip"] = "Snipew/Mawksmwan Wifles"
L["eft_subcat_smg"] = "Suwubmawwine Guwns"
L["eft_subcat_pist"] = "Pistows"
L["eft_subcat_melee"] = "⠀Mewwee"
L["eft_subcat_grenades"] = "⠀Gwenads  aawnd gwenade waunchew uwu"

-- [[ Weapon Classes ]]
L["eft_class_weapon_singleshot"] = "Single-shot Wifle"
L["eft_class_weapon_boltsg"] = "Bowt-actiowon Showtgun"
L["eft_class_weapon_pist"] = "Pistow"
L["eft_class_weapon_revol"] = "Rowowwer"
L["eft_class_weapon_megapist"] = "Machwine Pistow"
L["eft_class_weapon_smg"] = "Suwubmawwine Guwn"
L["eft_class_weapon_ar"] = "Awwault Wifle"
L["eft_class_weapon_carb"] = "Cawwbine Wifle"
L["eft_class_weapon_semisg"] = "Semi-autowo Showtgun"
L["eft_class_weapon_pumpsg"] = "Puwump Showtgun"
L["eft_class_weapon_lmg"] = "Liwwt Machwine Guwn"
L["eft_class_weapon_boltsnip"] = "Bowt-actiowon Sniper Wifle"
L["eft_class_weapon_marks"] = "Mawksmwan Wifle"
L["eft_class_weapon_dualsg"] = "Duwal-mowode Showtgun"
L["eft_class_weapon_melee"] = "Mewwee weapwon"

L["eft_class_weapon_melee"] = "Mewwee weapwon"
L["eft_class_weapon_grenade"] = "Hawand Gwenad owo"
L["eft_class_weapon_flashbang"] = "Fwawh Bawang Gwenad >w<"
L["eft_class_weapon_improvised_grenade"] = "Impwowised Hand Gwenad"
L["eft_class_weapon_stun"] = "StUwUn Gwenad"
L["eft_class_weapon_smoke"] = "SmOwOke Gwenad"
L["eft_class_weapon_grenadelauncher"] = "Gwenad wauncheww"

-- [[ Weapon Display Names ]]
L["eft_weapon_rsh12"] = "WShh-12"
L["eft_weapon_ash12"] = "AShh-12"
L["eft_weapon_toz106"] = "TOWww-106"
L["eft_weapon_ak74"] = "AK-74"
L["eft_weapon_ak74n"] = "AK-74N"
L["eft_weapon_ak74m"] = "AK-74Mwa"
L["eft_weapon_aks74"] = "AKS-74"
L["eft_weapon_aks74n"] = "AKS-74N"
L["eft_weapon_aks74u"] = "AKS-74Uwu"
L["eft_weapon_aks74un"] = "AKS-74UwuN"
L["eft_weapon_aks74ub"] = "AKS-74UBoo"
L["eft_weapon_ak101"] = "AK-101"
L["eft_weapon_ak102"] = "AK-102"
L["eft_weapon_ak103"] = "AK-103"
L["eft_weapon_ak104"] = "AK-104"
L["eft_weapon_ak105"] = "AK-105"
L["eft_weapon_akm"] = "AKMwa"
L["eft_weapon_akmn"] = "AKMN"
L["eft_weapon_akms"] = "AKMSs"
L["eft_weapon_akmsn"] = "AKMSN"
L["eft_weapon_pp1901"] = "PP-19-01 \"OWOWityaw\""
L["eft_weapon_rpk16"] = "WPK-16"
L["eft_weapon_saiga9"] = "Saigawa-9"
L["eft_weapon_saiga12k"] = "Saigawa 12ga wew.10"
L["eft_weapon_vpo136"] = "WPO-136 \"UWUpr-KM\""
L["eft_weapon_vpo209"] = "WPO-209"
L["eft_weapon_mosininf"] = "MOwOsin wifle (Inwantwy)"
L["eft_weapon_mosinsnip"] = "MOwOsin wifwe (Snipew)"
L["eft_weapon_ks23"] = "TOWw KS-23M"

L["eft_weapon_rdg2b"] = "WDG-2B"
L["eft_weapon_rgd5"] = "WGD-5"
L["eft_weapon_rgn"] = "WGN"
L["eft_weapon_rgo"] = "WGO"
L["eft_weapon_vog17"] = "OwOG-17 Khattabka"
L["eft_weapon_vog25"] = "OwOG-25 Khattabka"
L["eft_weapon_zarya"] = "Z-zawyaaa"

L["eft_weapon_6x5"] = "6Khhhh5 Bawonewt"
L["eft_weapon_a2607"] = "Barrws uwu"
L["eft_weapon_a2607d"] = "Barrrws uwu Damascus"
L["eft_weapon_camper"] = "Cawampew axee"
L["eft_weapon_freeman"] = "Fweeman cwowbaw"
L["eft_weapon_cultist"] = "Cuwtist kniwe >.<"
L["eft_weapon_mpl50"] = "MPw-50 entw tOwOl"
L["eft_weapon_rebel"] = "Wed Webew icew piwck"
L["eft_weapon_sp8"] = "SP-8 Mawchewte"
L["eft_weapon_taiga"] = "UwUSw Tawga-1"
L["eft_weapon_wycc"] = "Antiwk axe uwu"

L["eft_weapon_veresk"] = "SW-2Mwa \"UWUresk\""
L["eft_weapon_gyurza"] = "SW-1MwaP GyuwwzA"
L["eft_trivia_manuf_tsniitochmash"] = "TsNIITowochMawash >.<"
L["eft_trivia_calibr_9x21"] = "9x21mm GyuwwzA!"

L["eft_hud_full"] = "Fuwl :3"
L["eft_hud_empty"] = "Emptwy >.<"
L["eft_hud_nearlyfull"] = "Neawwy fuwl"
L["eft_hud_aboutfull"] = "Abuwut haww >w<"
L["eft_hud_lessthanhlaf"] = "Lewss twan haww"
L["eft_hud_almostempty"] = "Awmowst emptwy !"
L["eft_hud_none"] = "None uwu"
L["eft_hud_malf"] = "Mawwwunktiwon!!!! \""
L["eft_hud_misfire"] = "Miwwfiwe :3"
L["eft_hud_eject"] = "Faiwuwe to ewect owo"
L["eft_hud_feed"] = "Faiwuwe to fewd >w<"
L["eft_hud_bolt"] = "Bowt jam !!"
L["eft_hud_missing"] = "Miwwing cwiticawal pawts owo"

-- [[ Weapon descs ]] fuckkkkkkkk
-- L["eft_weapon_vpo209"] = "VPO-209"

