$modelname "weapons/arc9/darsu_eft/mods/sok12_340_mount.mdl"
 
$scale 40

$bodygroup "body"
{
	studio "mount_cust_custom_guns_short_rail_section_LOD0_0.smd"
}

$surfaceprop "weapon"

$cdmaterials "models/weapons/arc9/darsu_eft/mods"

// $attachment "flashlight" "flashlight" 0 0 0 rotate 0 0 90
// $attachment "laser" "laser" 0 0 0 rotate 0 0 90

$sequence "idle" {
	"mount_cust_custom_guns_short_rail_section_LOD0_0.smd"
	fps 30
}